### PR TITLE
Disable ajaxConversion in widget.

### PR DESCRIPTION
**Pull request by bupy7**
This for disable ajaxConversion if by default ajaxConversion is true and saveTimezone and displayTimezone is set:

```php
'displayTimezone' => 'Europe/Minsk',
'saveTimezone' => 'UTC',
'ajaxConversion' => true,
```

Now for disable ajaxConversion of FORMAT_DATE I do following:

```php
echo $form->field($phistoryModel, 'date_wedding')->widget(DateControl::className(), [
    'type' => DateControl::FORMAT_DATE,
    'ajaxConversion' => false,
    'saveTimezone' => false,
    'displayTimezone' => false,
]);
```

if to DateControl content following code:

```php
        if (!isset($this->displayTimezone)) {
            $this->displayTimezone = $this->_module->getDisplayTimezone();
        }
        if (!isset($this->saveTimezone)) {
            $this->saveTimezone = $this->_module->getSaveTimezone();
        }
```

### CODE REVIEW

**Comment by kartik-v** [comment]
The date conversion will not work properly without ajax if you set timezone.

**Comment by bupy7** [comment]
This is simply in case when need not conversion of date. In another only make following:

if global setting:

```php
'displayTimezone' => 'Europe/Minsk',
'saveTimezone' => 'UTC',
'ajaxConversion' => true,
```

then in widget:

```php
echo $form->field($phistoryModel, 'date_wedding')->widget(DateControl::className(), [
    'type' => DateControl::FORMAT_DATE,
    'saveTimezone' => 'UTC',
    'displayTimezone' => 'UTC',
]);
```

**Comment by bupy7** [comment]
how me disable ajaxConversion if not this method? but ajaxConversion by default in global settings file must be equal TRUE.

**Comment by bupy7** [comment]
I can disable ajaxConversion in the following option:

```php
echo $form->field($model, 'date')->widget(DateControl::className(), [
    'type' => DateControl::FORMAT_DATE,
    'pluginOptions' => [
        'url' => '',
        'saveTimezone' => null,
        'dispTimezone' => null,
    ],
]);
```

This is also work.

**Comment by kartik-v** [comment]
Yes if you do not use timezones... you can disable ajaxConversion. But note that you must use standard PHP date formats and NOT ICU format.

**Pull request closed without merging**
