### PR TITLE
Fix DateTime and Time parsing

### PR DESCRIPTION
**Pull request by alexander-suter**
This should fix the issue #57 

@kartik-v Is it possible, that you take this pull request and releasing a new bug fix version? Thank you!

### CODE REVIEW

**Comment by kartik-v** [comment]
Do not understand this PR... there is no `reqType` property in the `datecontrol.js` plugin.

**Comment by alexander-suter** [comment]
Uhh.

My composer.lock says that I've installed version v1.9.1 of kartik-v/yii2-datecontrol
and in my datecontrol.js was on line 38 the following code:
```javascript
vType = self.reqType, vDispFormat = self.dispFormat, vSaveFormat = self.saveFormat,
````
Maybe kartik-v/yii2-datecontrol was retagged?!

I cleared cache with my composer and removed vendor. After that I did composer install. In datecontrol.js is reqType still there. Also when I open datecontrol.js in my local composer cache. The current stable version v1.9.1 has reqType in datecontrol.js
...

**Comment by alexander-suter** [comment]
Maybe you revert this pull request and just release v1.9.2 from the current head?

**Comment by kartik-v** [comment]
The latest release v1.9.2 is tagged... you can pick it via composer now.

**Comment by alexander-suter** [comment]
Great! Thank you!

**Pull request closed without merging**
